name: CI

on:
  schedule:
    - cron: '0 0 * * 1,4'  # Run at midnight every Monday and Thursday
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.13'

      - name: Install godog
        run: |
          go install github.com/cucumber/godog/cmd/godog@latest
          export PATH=$PATH:$(go env GOPATH)/bin

      - name: Run godog tests
        run: |
          godog -format=pretty ./features


      - name: Upload Test Report
        uses: actions/upload-artifact@v3  # Updated version
        with:
          name: godog-test-report
          path: test/report/cucumber_report.html  # Adjust the path based on where your report is saved

      - name: Send report to Slack
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}  # Your Slack Bot User OAuth Token
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "Godog test report available: <.html>"}' \
          https://slack.com/api/chat.postMessage
