name: CI

on:
  schedule:
    - cron: '0 0 * * 1,4'  # Run at midnight every Monday and Thursday
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.13'

      - name: Install godog and HTML report generator
        run: |
          go install github.com/cucumber/godog/cmd/godog@latest
          go install github.com/your-username/go-cucumber-html@latest  # Replace with the actual HTML report generator
          export PATH=$PATH:$(go env GOPATH)/bin

      - name: Run godog tests
        run: |
          godog -f cucumber:test/report/cucumber_report.json ./features  # Generate Cucumber report

      - name: Generate HTML Report from JSON
        run: |
          go-cucumber-html test/report/cucumber_report.json test/report/cucumber_report.html  # Adjust this as needed

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: test/report/cucumber_report.json  # Adjust this path if needed

      - name: Send report to Slack
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}  # Your Slack Bot User OAuth Token
        run: |
          REPORT_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts"  # Link to the artifacts
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "Godog test report available: '"${REPORT_URL}"'"}' \
          https://slack.com/api/chat.postMessage
