name: Deploy HTML Report to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.13'  # Make sure this matches your testing version

      - name: Move Report to Publish Directory
        run: |
          mkdir -p ./public
          cp test/report/cucumber_report.html ./public/  # Move the generated report to the public directory

      - name: Upload HTML Report to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public  # This should point to the directory where your report is stored

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
